[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[[bin]]
name = "calculate"
path = "src/bin/calculate.rs"
[[bin]]
name = "read_file"
path = "src/bin/read_file.rs"
